name: Label Trigger Workflow

on:
  pull_request: {}

jobs:
  handle-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check Label Name
        run: |
          echo "full_name: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "repo ${{ github.repository }}"
